In [102]:
#pipeline
from  sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [103]:
steps=[('Standard_scaler',StandardScaler()),
       ('Logistic_reg',LogisticRegression())]

In [104]:
pipe=Pipeline(steps)

In [105]:
pipe

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('Logistic_reg', LogisticRegression())])

In [106]:
from sklearn import set_config
set_config(display="diagram")
pipe

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('Logistic_reg', LogisticRegression())])

In [107]:
#creating a dataset
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000)
x.shape

(1000, 20)

In [108]:
x

array([[-1.06628214e+00, -1.28316922e+00,  7.74742075e-02, ...,
        -1.75161257e+00,  9.24590778e-01,  3.67756914e-01],
       [-4.58003033e-01,  3.69326102e-01,  5.21119340e-01, ...,
        -1.82665453e+00,  8.17621858e-01, -7.28567523e-01],
       [-1.69506061e+00,  7.54589063e-01, -3.42691013e-04, ...,
         3.68118369e-01,  7.25982566e-01,  6.24665567e-01],
       ...,
       [-2.00366500e+00, -3.93897817e-01,  1.99038530e-01, ...,
         1.22938881e+00, -3.23080599e-01, -5.84261126e-01],
       [ 2.45600355e-01, -8.79168632e-01,  1.20893806e+00, ...,
         5.69291958e-01,  2.07210523e-01,  1.92369638e+00],
       [-2.52486714e-02, -6.02699834e-01, -1.79288366e+00, ...,
         1.61172758e-01, -1.08400021e+00, -1.44782483e-01]])

In [109]:
y

array([1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,

In [110]:
#train and test the model
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [111]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('Logistic_reg', LogisticRegression())])

In [112]:
pipe.predict(x_test)

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [113]:
#Example 2

In [114]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [115]:
steps=[('scalling',StandardScaler()),
       ('PCA',PCA(n_components=3)),
       ('SVM',SVC())
       ]

In [116]:
pipe2=Pipeline(steps)

In [117]:
pipe2.fit(x_train,y_train)
pred=pipe2.predict(x_test)
pred

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1])

In [118]:
#creating diff pipeline for numeric and categorical data and at the end combine all the pipeline
from sklearn.impute import SimpleImputer
import numpy as np
numeric_processor=Pipeline(steps=[('imputer',SimpleImputer(missing_values=np.nan,strategy='mean')),
                                  ('scalling',StandardScaler())])

In [119]:
numeric_processor

Pipeline(steps=[('imputer', SimpleImputer()), ('scalling', StandardScaler())])

In [120]:
from sklearn.preprocessing import OneHotEncoder
cat_processor=Pipeline(
    steps=[('imputation_constant',SimpleImputer(fill_value="missing",strategy='constant')),
                                  ("ohehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [121]:
cat_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('ohehot', OneHotEncoder(handle_unknown='ignore'))])

In [122]:
from sklearn.compose import ColumnTransformer

preprocessor=ColumnTransformer([("categorics",cat_processor,["gender","City"]),
                   ("numeric",numeric_processor,['age','height'])]
)

In [123]:
preprocessor

ColumnTransformer(transformers=[('categorics',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('ohehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numeric',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scalling',
                                                  StandardScaler())]),
                                 ['age', 'height'])])

In [124]:
from sklearn.pipeline import make_pipeline
pipe_final=make_pipeline(preprocessor,LogisticRegression())

In [125]:
pipe_final

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorics',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('ohehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scalling',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])